### ISSUE TITLE
make does not compile all required files

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-casacore#13] opened 2021-04-24 08:03 UTC
After running `make`, we'd normally run `make install` to just copy files to the install directory. However, `make install` also ends up compiling a bunch of files. In fact, every time you run `make`, the same files are compiled.

The problem is that running `sudo make install` now results in part of the build directory having root ownership

**Comment by pford** [comment] 2022-03-01 18:15
The additional compiling was caused by patching stdcasa/variant.cc **after** compiling the dependent source code.  This has been fixed in casa6, so the initial build in `make` will be sufficient and `make install` only installs.

This is fixed in branch `bump-casa6-02-2022` to update the casa6 commit.  This branch is currently using a casa6 branch commit, waiting for it to be merged to casa6 master.

**Comment by kswang1029** [comment] 2022-03-08 05:58
confirm on macOS Monterey, `sudo make install` does not have extra compiling stages.

**Closed** 2022-03-09 02:35 UTC
Labels: bug
